name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development
    paths:
      - 'notebooks/**'

jobs:
  run-notebook-in-development-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: Create CI environment
      run: |
        python3 -m venv .venv-ci
        .venv-ci/bin/pip install --quiet jupyter 'kfp==1.8.22'

    - name: Connect to local server and run the Notebook
      run: |
        # Execute the Jupyter Notebook and overwrite the existing file with the results
        .venv-ci/bin/jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb
